### ISSUE TITLE
Deprecate this module on NPM?

### ISSUE THREAD

**Issue by broofa** [heikomat/uuid-browser#1]
Given that "all the code in this package comes from the `uuid` project" can I politely suggest that you `npm deprecate` this module?  With a message to the effect of, "Use the `uuid` module instead"?

One specific reason for this is that the code you're publishing is known to have issues due to it's use of `Math.random()`.  The official `uuid` project stopped using Math.random() several versions ago for this reason.

**Comment by broofa** [comment]
[Closing out issues I've authored that appear to be stagnant.]

**Comment by SimenB** [comment]
@heikomat might be worth doing this - the module has 3.5M downloads a week (`@storybook/addon-actions` has [now](https://github.com/storybookjs/storybook/pull/22037) migrated over to `uuid`, so that number is likely to stop growing. But still 🙂)

**Comment by heikomat** [comment]
What the heck?
Sorry for not anwering @broofa, must have missed the email.
And @SimenB you're 100% correct, i should deprecate this.

I just needed some uuids in a browser 6 years ago and then forgot about this package. People should NOT be using it.
It has never been updated and there are better alternatives by now

1. Browsers can now natively create v4 uuids: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
2. The original uuid-package this is copied from exports proper browser-builds since version [7.0.1](https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md#701-2020-02-25)

Will deprecate it sometime this week

**Comment by heikomat** [comment]
I `npm deprecate`d the package and added a [deprecation-message to the readme](https://github.com/heikomat/uuid-browser/blob/f0f0efd67693ce0a78a706d4e69351897ebac2dd/README.md#%EF%B8%8F-this-is-deprecated).

Will now archive the repository
